services:
  nginx:
    image: nginx:latest
    container_name: chatalot_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../tls:/etc/nginx/certs:ro
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

  frontend:
    container_name: chatalot_frontend
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    image: chatalot/frontend:latest
    ports:
      - "5173"
    env_file:
      - ./frontend.env
    depends_on:
      - backend
    restart: unless-stopped
  
  backend:
    container_name: chatalot_backend
    build:
      context: ../../backend
      dockerfile: Dockerfile
    image: chatalot/backend:latest
    ports:
      - "3000"
    env_file:
      - ./backend.env
    depends_on:
      database:
        condition: service_healthy
    restart: unless-stopped

  database:
    container_name: chatalot_database
    image: mongo:5.0
    ports:
      - "27017"
    volumes:
      - chatalot-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwerty
      MONGO_INITDB_DATABASE: chatalot
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  chatalot-data: